image: docker

services:
  - docker:dind


variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""


stages:
  - prepare
  - d_login
  - d_build
  - d_push


preparing:
  stage: prepare
  script:
    #- uname -a  #alpine'da mı çalışıyor diye baktım
    - apk update
    - apk add --no-cache curl
    #- curl --version
    #- apk add --no-cache docker-cli  #başta alpine image'ı için kuruyordum, direkt docker image'ına geçince gerek kalmadı.
  only:
    - main

login:
  stage: d_login
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login $DOCKER_REGISTRY --username $DOCKERHUB_USERNAME --password-stdin
  only:
    - main


build:
  stage: d_build
  script:
    - docker --version
    - docker build -t pyouck/basic_todo_flask:latest .
    - docker images
    - docker tag pyouck/basic_todo_flask:latest pyouck/basic_todo_flask:1.4
    - docker images

  only:
    - main

push:
  stage: d_push
  script:
    - docker --version
    - docker login
    - docker push pyouck/basic_todo_flask:1.4
  only:
    - main
